server:
  port: 8088
spring:
  application:
    name: xtool-common
  datasource:
    password: 123456
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.140.128:3306/saas_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
mybatis-plus:
  mapper-locations: classpath*:sqlmap/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

