server:
  port: 8080
spring:
  application:
    name: xtool-common
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.140.128:3306/shardingjdbc_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          park_dept:
            actual-data-nodes: ds0.park_dept_$->{[6456419921961160704,6290020514064764928]}
  #          actual-data-nodes: ds0.park_dept_TEST
            key-generator:
              column: id
              type: SNOWFLAKE
            table-strategy:
              inline:
                algorithm-expression: park_dept_$->{park_id}
                sharding-column: park_id
    props:
      sql:
        show: true